version: '3'

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /Users/doukim/data/db-data
      type: none
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      device: /Users/doukim/data/wp-data
      type: none
      o: bind

networks:
  intra:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42

    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - intra

    tty: true
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42

    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www
    networks:
      - intra

    tty: true
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42

    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - intra
    tty: true
    restart: always
