# FROM debian:bullseye

# RUN apt-get update -y && apt-get upgrade -y
# RUN apt-get install -y mariadb-server systemd

# RUN mkdir -p /var/run/mysqld
# RUN chown -R mysql:mysql /var/run/mysqld
# RUN chmod 777 /var/run/mysqld

# EXPOSE 3306

# COPY ./tools/50-server.cnf /etc/mysql/mariadb.conf.d/

# COPY ./tools/db-script.sh /
# RUN chmod +x /db-script.sh

# # CMD ["/db-script.sh"]

FROM debian:bullseye

RUN apt update -y && apt upgrade -y && apt-get install -y mariadb-server \
	curl

RUN apt-get install systemd -y

COPY ./tools/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/db-script.sh /

RUN chmod +x /db-script.sh

EXPOSE 3306

# CMD ["/db-script.sh"]