FROM debian:bullseye

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx && apt-get -y install openssl -y

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=KR/L=Seoul/O=42Seoul/OU=student/CN=doukim"

COPY ./conf/default /etc/nginx/sites-available/

EXPOSE 443

# CMD ["nginx", "-g", "daemon off;"]